%define COLOR_BLACK     0
%define COLOR_BLUE      1
%define COLOR_GREEN     2
%define COLOR_CYAN      3
%define COLOR_RED       4
%define COLOR_MAGENTA   5
%define COLOR_BROWN     6
%define COLOR_LTGRAY    7
%define COLOR_GRAY      8
%define COLOR_LTBLUE    9
%define COLOR_LTGREEN   10
%define COLOR_LTCYAN    11
%define COLOR_LTRED     12
%define COLOR_LTMAGENTA 13
%define COLOR_YELLOW    14
%define COLOR_WHITE     15

%define FG(c) (c)
%define BG(c) ((c) << 4)
